services:
  postgres-db:
    image: postgres:16-alpine
    container_name: coworking_postgres_db
    restart: always
    environment:
      POSTGRES_DB: coworking_db
      POSTGRES_USER: coworking_user
      POSTGRES_PASSWORD: coworking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_coworking_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coworking_user -d coworking_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_coworking_data:
    driver: local